project:
  type: website

website:
  title: "DP-Next"
  site-url: "https://dp-next.github.io/"
  repo-url: "https://github.com/dp-next/dp-next.github.io"
  navbar:
    pinned: true
    left:
      - text: "Researcher"
        href: index.qmd
      - text: "Participant"
        menu:
        - text: "Participant 🇬🇧"
          href: en/participant.qmd
        - text: "Deltager 🇩🇰"
          href: da/participant.qmd
        - text: "Luttakari 🇫🇴"
          href: fo/participant.qmd
        - text: "Peqataasoq 🇬🇱"
          href: kl/participant.qmd
      - text: "Work packages"
        menu:
        - wp1/index.qmd
        - text: "WP2: Risk Prediction"
          href: wp2.qmd
        - text: "WP3: Heterogeneity"
          href: wp3.qmd
        - text: "WP4: Intervention Development"
          href: wp4.qmd
      - text: Events
        href: events/index.qmd
      - text: Who We Are
        href: who-we-are.qmd
      - text: Outputs
        href: outputs.qmd
      - text: Support
        href: support.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/"
  sidebar:
    - title: "Participant 🇬🇧"
      contents:
        - en/participant.qmd
        - en/participant-questionnaire.qmd
        - en/participant-clinical.qmd
    - title: "Deltager 🇩🇰"
      contents:
        - da/participant.qmd
        - da/participant-questionnaire.qmd
        - da/participant-clinical.qmd
    - title: "Luttakari 🇫🇴"
      contents:
        - fo/participant.qmd
        - fo/participant-questionnaire.qmd
        - fo/participant-clinical.qmd
    - title: "Peqataasoq 🇬🇱"
      contents:
        - kl/participant.qmd
        - kl/participant-questionnaire.qmd
        - kl/participant-clinical.qmd

format:
  html

bibliography: references.bib
csl: vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true
