---
title: "Intervention"
---

## Intervention suna pillugu imaqarpa?

DP-Nextip anguniagaanut pingaarnernut ilaavoq type 2-diabetesimik pinaveersaartitsinermut periusissianik nutaanik pitsaanerusunillu ineriartortitsineq.

Apeqqutinik immersugassanit, peqqissutsimut nalunaarsuiffinnit aammalu kliniskimik misissuinernit paasissutissat tunngavigalugit ilisimatusartut navianartorsiortut assigiinngitsut naapertorlugit pinaveersaartitsinermik periusissianik ineriartortitsissapput. Periusissiat peqataasut, peqqinnissaqarfimmi sulisut aammalu ilisimatusartut suleqatigalugit ineriartortinneqassapput, qularnaarniarlugu ulluinnarni peqqinnissaqarfimmi atorneqarsinnaallutillu naleqqussarsinnaanissaat.

Interventioninik ineriartortitsineq ilaatigut ukununnga tunngassuteqarsinnaavoq:

- Peqqinnartunik inuusaaseqarnermik allannguinernik tapersersuineq
- Peqqinnissaqarfimmi pinaveersaartitsinerup malitseqartitsinerullu pitsanngorsarneri
- Inummut ataasiakkaamut navianartorsiortitsinerit naapertorlugit pinaveersaartitsinermi periutsinik nutaanik ineriartortitsineq

Anguniagaavoq piujuartitsisumik pinaveersaartitsinermik periusissianik ineriartortitsineq, ulluinnarni atorneqarsinnaasunik aammalu type 2-diabetesimik ineriartortitsinissamut navianartorsiortitsinerup annikillisarnissaanut iluaqutaasunik.
