---
title: "Kliniskimik misissuineq"
---

## Kliniskimik misissuinerni suna ingerlanneqartarpa?

Peqataasut ilaat Steno Diabetes Centerimi kliniskimik misissuinermut aggersarneqassapput. Siunertaavoq kliniskimik kohortimik nutaamik pilersitsineq, peqqissaartumik peqqissutsimik uuttuutinik imaqartumik, diabetesimik navianartorsiortitsinermut atatillugu siusissukkut biologiskimik allannguutit pillugit paasinninnerulernissaq anguniarlugu.

Misissuineq akunnerit sisamat missaannik sivisussuseqarpoq aammalu makkuninnga imaqarsinnaavoq:

- Takissusermik, oqimaassusermik timillu qanoq inissisimaneranik uuttuisarneq
- Aaversinnerit aammalu aakkut sukkortarneranik uuttuisarneq
- Glukosebelastningstest
- Tingup orsuanik uuttuisarneq
- Aap naqitsineranik aammalu uummatip taqqatigullu qanoq issusaanik uuttuisarneq
- Timimik aalatitsisarnerup nalilersorneqarnera
- Biologiskinik misissugassanik ilisimatusarnermut biobankimi toqqorsineq

Misissuinernit taakkunannga ilisimatusartut inuit akornanni diabetesimik navianartorsiortitsinerit assigiinngissutaat kiisalu nappaatip ineriartortarneranut siusissukkut biologiskimik ilisarnaatit paasiniarsinnaavaat.

Kliniskimik misissuinermut peqataaneq nammineq kajumissutsimik tunngaveqarpoq aammalu immikkut akuersissuteqarnissaq piumasaqaataavoq.
